ITS-UofIowa/sitenow_custom_profile

- sitenow.install
> Added auth mappings update hook

- sitenow.install
> change update hook number to fix fatal error

- .travis.yml
- sitenow.info
- sitenow.make.yml
This PR adjusts the build artifact to:
- remove git history from profile dependencies
- write patches.txt files
- write version numbers to info files
> GitHub releases

- .travis.yml
- sitenow.info
- sitenow.make.yml
Reverts ITS-UofIowa/sitenow_custom_profile#52
> Revert "GitHub releases"

- includes/sitenow.content-types.inc
- includes/sitenow.file.inc
- includes/sitenow.roles.inc
- sitenow.install
> Setup private files on install

- sitenow.make.yml
> extract dest subtree from respondjs library

- drupal-org-core.make.yml
- modules/custom/ovpred_common_modules/ovpred_blocks/ovpred_blocks.module
- sitenow.make.yml
Includes:
- https://github.com/ITS-UofIowa/sitenow_custom_profile/issues/79
- https://github.com/ITS-UofIowa/sitenow_custom_profile/issues/76
- #80 
- #84
> February 2017 updates

- .gitignore
> Add ds_store to gitignore

- sitenow.make.yml
This address issue https://github.com/ITS-UofIowa/sitenow_custom_profile/issues/91
> March updates

- themes/fo_common/fo_common.info
- themes/fo_common/template.php
- themes/fo_common/templates/page.tpl.php
Add aria landmarks to the fo_common theme.
This PR is purposely based on the include branch because of an issue with template files being ignored in the current master branch.
This PR could be merged into the include branch or merged into master after include.
> add aria landmarks

- sitenow.install
Many theme files have changed including some blank/unused files that were deleted. I didn't notice any issues locally but thought an RR might be a good idea. Maybe a CC would suffice?
> cc all for 3.x changes

- themes/fo_common/templates/html.tpl.php
F&O is sponsoring this change which will affect all of their sites. 
I copied html.tpl.php from Adaptive theme and changed
`<div id="skip-link">`
to
`<div id="skip-link" role="region" aria-label="skip-link">`
That's it :)
> Add landmark for skip link

- modules/custom/engineering_shared/engineering_shared_people/plugins/content_types/engineering_shared_people.inc
forgot to change this to the production value. sorry...
> changing endpoint value to production url.

- sitenow.install
> Turn off page compression.

- sitenow.make.yml
> July 2017 Updates

- sitenow.install
tested and completed [this enhancement](https://github.com/ITS-UofIowa/sitenow_custom_profile/issues/81)
> fix default pathing

- sitenow.info
- sitenow.install
adding functionality for [this enhancement](https://github.com/ITS-UofIowa/sitenow_custom_profile/issues/82) with a default of 10 revisions kept.
> added node revision delete on isntall to keep revisions from piling up

- sitenow.make.yml
Addresses security issues:
- https://www.drupal.org/node/2902604
- https://www.drupal.org/node/2902596
> Security updates

- modules/custom/engineering_shared/engineering_fpp_widgets/engineering_fpp_widgets.features.field_instance.inc
- themes/engineering/includes/html.inc
- Force IE to not use compatibility mode
- Use original image size for fancybox view.
> Changes for Engineering Theme/Module

- modules/custom/engineering_shared/engineering_shared_content_types/engineering_shared_content_types.features.field_instance.inc
- modules/custom/engineering_shared/engineering_shared_content_types/engineering_shared_content_types.info
- modules/custom/engineering_shared/engineering_shared_content_types/engineering_shared_content_types.module
- modules/custom/engineering_shared/engineering_shared_content_types/engineering_shared_content_types.strongarm.inc
- modules/custom/engineering_shared/engineering_shared_content_types/theme/node--article--grid--dept.tpl.php
- modules/custom/engineering_shared/engineering_shared_content_types/theme/node--article--teaser--dept.tpl.php
- modules/custom/engineering_shared/engineering_shared_feeds/engineering_shared_feeds.feeds_importer_default.inc
- modules/custom/engineering_shared/engineering_shared_feeds/engineering_shared_feeds.feeds_tamper_default.inc
- modules/custom/engineering_shared/engineering_shared_feeds/engineering_shared_feeds.info
- modules/custom/engineering_shared/engineering_shared_field_bases/engineering_shared_field_bases.features.field_base.inc
- modules/custom/engineering_shared/engineering_shared_field_bases/engineering_shared_field_bases.info
- articles import maps teaser/grid image style in a separate field for use/display.
> import/use cropped image for articles.

- sitenow.profile
> return 403 for /node

- sitenow.make.yml
> update contrib and custom projects

- sitenow.make.yml
> december 2017 updates #209

- drupal-org-core.make.yml
- sitenow.make.yml
Update Drupal core, sitenow_paragraphs, and add uiowa_alerts.
> March 2018 updates

- sitenow.make.yml
> uiowa_bar 7.x-2.6

- sitenow.make.yml
> remove proj4js

- sitenow.make.yml
This has been committed to the link project and will be useful for a project that I'm working on: https://www.drupal.org/project/link/issues/2718563
> patch link to use link_field in fapi

- .gitignore
- modules/custom/sitenow_slick_a11y/README.md
- modules/custom/sitenow_slick_a11y/js/sitenow_slick_a11y_dots.behavior.js
- modules/custom/sitenow_slick_a11y/js/sitenow_slick_a11y_events.behavior.js
- modules/custom/sitenow_slick_a11y/sitenow_slick_a11y.info
- modules/custom/sitenow_slick_a11y/sitenow_slick_a11y.module
adds title and aria-labels to slick slideshow dots and arrows.
> added slick a11y module
